### ISSUE TITLE
Uncategorized vs. Categorized display?

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#10]
The questions that now have LOs assigned to them (at least the target LO) are now appearing as individuals above the Uncategorized section, which I believe is intended behavior. When I click on one however, the question itself doesn't populate below it. Additionally, the question remains in the uncategorized section. 

![uncategorized](https://cloud.githubusercontent.com/assets/1149890/15687433/b2a45520-2742-11e6-8208-ce2df46fa293.png)

**Comment by chadlieberman** [comment]
This is resolved based on your response to the other issue. Thanks!

**Comment by coleshaw** [comment]
That’s because that’s not the intended behavior…(outcomes appearing above “uncategorized”)

The panels above “Uncategorized” are supposed to be “modules”, not “outcomes”... But I see that you’ve changed the organization, so I think we’re on the same page, now...
