### ISSUE TITLE
Item editing performance

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#16]
When I edit an item to change just a few characters in one of the answer choices and then save, it takes about 9 seconds to finish updating the problem and unlock the page. This delay makes the UX pretty frustrating. I'm not sure why it is so slow, but if that is unavoidable for some reason, can we make it async and use optimistic updates with reversion when the put/post fails?

**Comment by coleshaw** [comment]
Can you be more specific (which question / answer, etc.)? Is it every time you edit, regardless which question? The code is [already async](https://github.com/wombats-writing-code/fbw-components/blob/master/ItemAuthoring/modules/components/EditMultipleChoice.jsx#L460) and the modal should close as soon as you hit save, without locking or waiting for the PUT to finish. Perhaps there is something else going on, with a plugin/extension or a browser config?

I wasn't able to replicate this issue, and I would need to see 1) if others have it (have you confirmed with Dipa?), 2) more details about your setup. I just updated an answer on the dev server, and the PUT took < 1 second to complete...

![captura de pantalla 2016-06-07 a las 8 54 08 am](https://cloud.githubusercontent.com/assets/4930129/15858231/837b85b6-2c8d-11e6-8b94-6bba08d559f4.png)

**Comment by chadlieberman** [comment]
Yes, the overlay goes away immediately... but the page gets locked up, i.e., I can't click into a different feedback or drop down another question, etc.

Seems to happen on creation and editing at all times. It also occurs when I edit the feedback using the Feedback button. The delay is sometimes more or less than 9 seconds, but I don't think I've had any that have been less than 5 seconds.

I have not checked with Dipa.

I'm running Google Chrome 51.0.2704.63 on 64-bit Ubuntu 14.04.4 LTS.

Have you tried on the production server? I'm not sure why it would be different, but the delay is much less on the development site. Try adding feedback to one item clicking save, and then immediately opening the feedback for a different option --- you will experience the short delay even on development server. It is like that, but much longer, on production.

**Comment by coleshaw** [comment]
I think I see what you mean...it's not the process of saving the edits themselves. Example: I edited feedback on the MAT 1 question Target: Manipulate fractional equations using the feedback modal, and the PUT was < 200 ms.

![captura de pantalla 2016-06-07 a las 9 33 46 am](https://cloud.githubusercontent.com/assets/4930129/15859382/f72d098a-2c92-11e6-8ee3-556c00b42843.png)

I edited using the "edit question" modal and the PUT was < 600 ms.

![captura de pantalla 2016-06-07 a las 9 32 36 am](https://cloud.githubusercontent.com/assets/4930129/15859391/02bc20f6-2c93-11e6-9446-075d3eb1961a.png)

However, there does seem to be rendering lockup (the modal is gone, but I cannot click on anything on the UI) -- I assume that is what you're referring to?

**Comment by chadlieberman** [comment]
Precisely.

**Comment by coleshaw** [comment]
Okay, please try again. We’ve refactored so it seems faster now…hopefully it will scale well.

**Comment by chadlieberman** [comment]
That's approximately infinity better. Thanks!
