### ISSUE TITLE
Cannot add new wrong answer choices in a row 

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-components#18]
Try this: open up a question with only 1 wrong answer choice. 

Add another wrong answer choice. 

Then try to add another wrong answer choice. It breaks. 

think the wrong answer component $key id is not getting filled -- see screenshot. 
![screen shot 2016-07-08 at 8 49 24 pm](https://cloud.githubusercontent.com/assets/2822290/16682282/e65ebcc4-454d-11e6-9322-8a8f593a0c73.png)

**Comment by coleshaw** [comment]
Should be fixed now
