### ISSUE TITLE
Editor doesn't show HTML attributes

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-components#21]
The editor doesn't show HTML attributes. But it does save them. Try this:
1. Put in an attribute, e.g. 1st screenshot, like class="my-class" or something. Toggle out of source mode. It's gone. Put it back. Save it. 
2. Open up console. It's there!  2nd screenshot.
3. Go and edit the question again. It's gone for good -- save it and check it in the console :(

Might be a nasty bug to fix. Not super high priority. 

![screen shot 2016-07-10 at 8 58 57 pm](https://cloud.githubusercontent.com/assets/2822290/16712688/996e6f7c-46e2-11e6-80aa-38250f0b1874.png)
![screen shot 2016-07-10 at 9 00 49 pm](https://cloud.githubusercontent.com/assets/2822290/16712689/a323a82a-46e2-11e6-9301-b754b4082b0f.png)

**Comment by coleshaw** [comment]
Hm, that’s interesting. That might be a CKEditor issue rather than our tool issue — I’d have to dig deeper into it. I save whatever CKEditor spits out, and do no massaging.

**Comment by coleshaw** [comment]
Okay, this should be fixed

**Comment by luwen-huang** [comment]
confirmed. that was very nice.
