### ISSUE TITLE
integrate xoces viz branch into master

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-components#23]
I've pushed a fully functional Dashboard component in the `with-viz` branch. But it fetches from a static json of outcomes, relationships and assessment items now. (Remember to `npm install` the new dependencies.)

Can you checkout that branch and help make the integrations to the stores? Then we can roll out all the new stuff this week. 

Up to you where to put this component. Right now it's just plunked on top, first thing on the page.

**Comment by coleshaw** [comment]
Where does this lie in terms of priority, relative to getting the Instructor App tied into stores?

**Comment by coleshaw** [comment]
Done. Can preview on the -dev site.
