### ISSUE TITLE
Outcome linkages do not persist when copying question

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#24]
We can open this for discussion, but I think we should copy the outcome linkages for the distractors when we copy a question (as a default). At some point soon, we are going to be creating duplicates, triplets, quadruplets, quintuplets, etc. of the questions we have in order to build up the bank of questions for each outcome. Although sometimes the distractors will change and their outcomes may change, I think that most of the time we will just be changing some numbers around. It would save us a lot of time if we didn't have to go back through and link each distractor again. Thoughts?

**Comment by coleshaw** [comment]
Probably should have invested in parameterized questions / feedback, if mostly you’re just changing numbers …

Otherwise that’s really a bug, because I thought that’s what the current implemented behavior should do. But looks like it’s setting the wrong parameter for wrong answers, so I can fix that.

**Comment by chadlieberman** [comment]
I'm not sure parameterizing questions, solutions, and distractors is
attainable. There are sometimes complex relationships among these things. I
think that could be a separate project in itself...

Chad E. Lieberman, Ph.D.
Independent Consultant
www.chadelieberman.com
(609) 577-5305

**Comment by coleshaw** [comment]
Should be fixed on production. You might have to clear your cache.
