### ISSUE TITLE
Default behavior of network visualization on module selection?

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#25]
What is the default behavior supposed to be for the network visualization in the authoring tool for _modules_? My understanding was that it would collect outcomes linked to that module and all children (and children of children, etc.) and show that network. It seems to just show the top level objectives right now.

**Comment by coleshaw** [comment]
Probably best answered by Luwen, but keep in mind that prerequisites != children … as far as I know, the fly-by-wire data does not actually include multiple children levels, it should only have 2 (modules -> outcomes). Everything else is outcome -> prerequisite outcome?

**Comment by luwen-huang** [comment]
can you give me an example of where a module's child(ren) doesn't show up? but yes, echoing what Cole said -- there's only 2 children levels -- module > outcome.

**Comment by chadlieberman** [comment]
Perhaps I still don't understand the intent of the module selection part of the viz tool. I thought I did after we had that long discussion about outcomes belonging to a module, etc, but now I am not sure again. My understanding was the following:

Let's say Module A has two learning objectives LO 1 and LO 2. LO 1 has 1 prerequisite learning objective PLO 1.1, and LO 2 has no prerequisite learning objectives. When Module A is selected in the viz tool, I expect to see bubbles for LO 1, LO 2, and PLO 1.1 (and I expect to see a line connecting LO 1 and PLO 1.1).

It seems that I am only seeing LO 1 and LO 2 as it stands now.

One example is the Sample Mission module Dipa and I have been putting together. I was interested to see whether or not any of the prerequisite outcomes were linked between the two highest-level outcomes in the module. When I select it in the viz tool, I only see those highest level outcomes and none of their prerequisites. (See attached.)

![image](https://cloud.githubusercontent.com/assets/1149890/17968559/78c81796-6a9b-11e6-89a0-6a8e40eaed05.png)

**Comment by luwen-huang** [comment]
But that's the expected behavior. looking at the Sample Mission module in
the authoring tool, I see that that module only contains 2 outcomes.

parent child relationships != prerequisite relationships. I think what
you're looking for is the ability to designate n arbitrary outcomes as
root(s).

[image: Inline image 2]

**Comment by chadlieberman** [comment]
How do we get a global picture of a module? For example, if we want to see what's going on in a module to identify places where we may have duplicate similar outcomes or if there are places that should probably have an additional outcome, how do we do that?

**Comment by luwen-huang** [comment]
that would be the module view, where you see only the outcomes belonging in
that module.

but it sounds like you also want to see outcomes that have prerequisite
relationships, but aren't necessarily in that module.

**Comment by chadlieberman** [comment]
My understanding was that the visualization tool would build the whole network. It seems that interpretation is wrong, based on the above discussion. Perhaps we can have a short discussion tomorrow on the call of how you are deciding which outcomes get assigned to a module.
