### ISSUE TITLE
Recommended change to module deletion behavior

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#26]
I propose that the Xoces tool be changed so that deletion of a module removes it but does not affect its child outcomes. These outcomes can be shared across modules and deleting one module can affect other modules in the current implementation. I just made this mistake on a minor scale, and I can restore things pretty easily, but it may lead to much bigger problems later on if we don't change it.

**Comment by coleshaw** [comment]
Changed and deployed, I tested on dev and it seemed to be fine -- let me know if you run into any issues.

**Comment by luwen-huang** [comment]
why would an outcome appear in more than one module? can you give me an
example of when that's the case?

**Comment by chadlieberman** [comment]
I think there are many instances when this _**could**_ happen, and that should be enough to warrant the change. For example, when we reorganize our outcomes into semantic modules from the Unit X based organization. Had we deleted the Unit X modules, I think all of the outcomes would have disappeared... Once faculty members start using Xoces, anything could happen =)
