### ISSUE TITLE
Speed at which edits made show up on user side?

### ISSUE THREAD

**Issue by dnshah** [wombats-writing-code/fbw-components#32]
I think this is a known issue, but just want to put this on the list so it can prioritized accordingly. The lag time between making an edit (or writing a new item) and actually seeing it on the user side is an issue. Particularly if we want faculty to start making edits on the tool, I can see this confusing them. @cjshawMIT @luwen-huang

**Comment by coleshaw** [comment]
@dnshah , we have some ideas for this, will try something and let you know.

**Comment by coleshaw** [comment]
@dnshah this should be faster now. Please let me know if you run into any funky issues, since I had a bug on my machine that I could not reproduce once I pushed the changes online.
