### ISSUE TITLE
Edits displaying inconsistently on authoring tool

### ISSUE THREAD

**Issue by dnshah** [wombats-writing-code/fbw-components#35]
It doesn't happen everytime, but yesterday and today, when edits are made to an item (stem, answer choices, solution), sometimes things display correctly, sometime not. I can't figure out a trend. I've been working on the Inventory Costing module in accounting. @cjshawMIT @luwen-huang

**Comment by coleshaw** [comment]
Okay, let me try to replicate it on my end … are you doing this on campus, at home, VPN, etc.?

**Comment by coleshaw** [comment]
Okay, let me try to replicate it on my end … are you doing this on campus, at home, VPN, etc.?

**Comment by dnshah** [comment]
Yesterday, on campus. Today, from Acela train wifi. Not on VPN.

I can’t figure out what triggers the non-updating scenario. The first question I edited, it didn’t update (visually, but pretty sure it must be updating on backend); then I edited 6 or 7 questions with no problem, then another question didn’t update…

Outcomes update just fine as long as you minimize the question and then re-expand it.

Darshita (Dipa) Shah, Ph.D.
Associate Director for Teaching and Learning
Teaching and Learning Lab, MIT
(617) 324-4503
Follow @MIT_TLL
TLL Blog: mitcogblog.nethttp://mitcogblog.net

On Oct 7, 2016, at 11:48 AM, cjshawMIT <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, let me try to replicate it on my end … are you doing this on campus, at home, VPN, etc.?

**Comment by coleshaw** [comment]
Hm, okay. Thanks for the added detail. I was running into a similar issue when running the app on my laptop, but only for wrong-answer LOs, but then it didn’t reappear after I deployed it to a server. Let me see.

To confirm, for all scenarios, when you refresh the page your changes show up?

**Comment by coleshaw** [comment]
Hm, okay. Thanks for the added detail. I was running into a similar issue when running the app on my laptop, but only for wrong-answer LOs, but then it didn’t reappear after I deployed it to a server. Let me see.

To confirm, for all scenarios, when you refresh the page your changes show up?

**Comment by dnshah** [comment]
Yes…I think...

On Oct 7, 2016, at 12:11 PM, cjshawMIT <notifications@github.com<mailto:notifications@github.com>> wrote:

To confirm, for all scenarios, when you refresh the page your changes show up?

**Comment by coleshaw** [comment]
Have a hack in place, will deploy soon and let you know. I can't replicate it exactly on my end, but this at least fixed the wrong-answerLO issue I saw, which I think is the same root-cause as the issue you're seeing.
