### ISSUE TITLE
InstructorApp: UX: if you select a mission on the sidebar when addMission is rendered, get mount conflicts?

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-components#7]
If you touch "Add Mission" and then click on an existing mission in the sidebar, you start getting warnings about "setState() can only update a mounted or mounting component". We should fix that and figure out where it's coming from...most likely one of the components (Add Mission?) is not getting unmounted properly.

**Comment by luwen-huang** [comment]
I can't replicate this. steps:
1) tapped on 'Add Mission'
2) tapped on existing mission in sidebar

--> no warnings.

**Comment by coleshaw** [comment]
Perhaps I inadvertently fixed this already, haha...closing for now. Keep an eye on this, though.
